/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * JInshanBodyShopApi
 * OpenAPI spec version: 1.0
 */
import { useMutation, useQuery } from "@tanstack/react-query";
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult,
} from "@tanstack/react-query";

import type {
  GetDownloadParams,
  PresignRequest,
} from "../jInshanBodyShopApi.schemas";

import { axiosInstance } from ".././axiosInstance";
import type { ErrorType, BodyType } from ".././axiosInstance";

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];

export const postOvh = (
  presignRequest: BodyType<PresignRequest>,
  options?: SecondParameter<typeof axiosInstance>,
  signal?: AbortSignal,
) => {
  return axiosInstance<string>(
    {
      url: `https://localhost:7035/Ovh`,
      method: "POST",
      headers: { "Content-Type": "application/json" },
      data: presignRequest,
      signal,
    },
    options,
  );
};

export const getPostOvhMutationOptions = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof postOvh>>,
    TError,
    { data: BodyType<PresignRequest> },
    TContext
  >;
  request?: SecondParameter<typeof axiosInstance>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof postOvh>>,
  TError,
  { data: BodyType<PresignRequest> },
  TContext
> => {
  const mutationKey = ["postOvh"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof postOvh>>,
    { data: BodyType<PresignRequest> }
  > = (props) => {
    const { data } = props ?? {};

    return postOvh(data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type PostOvhMutationResult = NonNullable<
  Awaited<ReturnType<typeof postOvh>>
>;
export type PostOvhMutationBody = BodyType<PresignRequest>;
export type PostOvhMutationError = ErrorType<unknown>;

export const usePostOvh = <TError = ErrorType<unknown>, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof postOvh>>,
      TError,
      { data: BodyType<PresignRequest> },
      TContext
    >;
    request?: SecondParameter<typeof axiosInstance>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof postOvh>>,
  TError,
  { data: BodyType<PresignRequest> },
  TContext
> => {
  const mutationOptions = getPostOvhMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
export const getDownload = (
  params?: GetDownloadParams,
  options?: SecondParameter<typeof axiosInstance>,
  signal?: AbortSignal,
) => {
  return axiosInstance<string>(
    { url: `https://localhost:7035/download`, method: "GET", params, signal },
    options,
  );
};

export const getGetDownloadQueryKey = (params?: GetDownloadParams) => {
  return [
    `https://localhost:7035/download`,
    ...(params ? [params] : []),
  ] as const;
};

export const getGetDownloadQueryOptions = <
  TData = Awaited<ReturnType<typeof getDownload>>,
  TError = ErrorType<unknown>,
>(
  params?: GetDownloadParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getDownload>>, TError, TData>
    >;
    request?: SecondParameter<typeof axiosInstance>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetDownloadQueryKey(params);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getDownload>>> = ({
    signal,
  }) => getDownload(params, requestOptions, signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getDownload>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetDownloadQueryResult = NonNullable<
  Awaited<ReturnType<typeof getDownload>>
>;
export type GetDownloadQueryError = ErrorType<unknown>;

export function useGetDownload<
  TData = Awaited<ReturnType<typeof getDownload>>,
  TError = ErrorType<unknown>,
>(
  params: undefined | GetDownloadParams,
  options: {
    query: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getDownload>>, TError, TData>
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getDownload>>,
          TError,
          Awaited<ReturnType<typeof getDownload>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof axiosInstance>;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetDownload<
  TData = Awaited<ReturnType<typeof getDownload>>,
  TError = ErrorType<unknown>,
>(
  params?: GetDownloadParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getDownload>>, TError, TData>
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getDownload>>,
          TError,
          Awaited<ReturnType<typeof getDownload>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof axiosInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetDownload<
  TData = Awaited<ReturnType<typeof getDownload>>,
  TError = ErrorType<unknown>,
>(
  params?: GetDownloadParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getDownload>>, TError, TData>
    >;
    request?: SecondParameter<typeof axiosInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};

export function useGetDownload<
  TData = Awaited<ReturnType<typeof getDownload>>,
  TError = ErrorType<unknown>,
>(
  params?: GetDownloadParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getDownload>>, TError, TData>
    >;
    request?: SecondParameter<typeof axiosInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getGetDownloadQueryOptions(params, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey;

  return query;
}
