/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * JInshanBodyShopApi
 * OpenAPI spec version: 1.0
 */
import { useQuery } from "@tanstack/react-query";
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseQueryOptions,
  UseQueryResult,
} from "@tanstack/react-query";

import type { WeatherForecast } from "../jInshanBodyShopApi.schemas";

import { axiosInstance } from ".././axiosInstance";
import type { ErrorType } from ".././axiosInstance";

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];

export const getWeatherForecast = (
  options?: SecondParameter<typeof axiosInstance>,
  signal?: AbortSignal,
) => {
  return axiosInstance<WeatherForecast[]>(
    { url: `https://localhost:7035/WeatherForecast`, method: "GET", signal },
    options,
  );
};

export const getGetWeatherForecastQueryKey = () => {
  return [`https://localhost:7035/WeatherForecast`] as const;
};

export const getGetWeatherForecastQueryOptions = <
  TData = Awaited<ReturnType<typeof getWeatherForecast>>,
  TError = ErrorType<unknown>,
>(options?: {
  query?: Partial<
    UseQueryOptions<
      Awaited<ReturnType<typeof getWeatherForecast>>,
      TError,
      TData
    >
  >;
  request?: SecondParameter<typeof axiosInstance>;
}) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetWeatherForecastQueryKey();

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof getWeatherForecast>>
  > = ({ signal }) => getWeatherForecast(requestOptions, signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getWeatherForecast>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetWeatherForecastQueryResult = NonNullable<
  Awaited<ReturnType<typeof getWeatherForecast>>
>;
export type GetWeatherForecastQueryError = ErrorType<unknown>;

export function useGetWeatherForecast<
  TData = Awaited<ReturnType<typeof getWeatherForecast>>,
  TError = ErrorType<unknown>,
>(
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getWeatherForecast>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getWeatherForecast>>,
          TError,
          Awaited<ReturnType<typeof getWeatherForecast>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof axiosInstance>;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetWeatherForecast<
  TData = Awaited<ReturnType<typeof getWeatherForecast>>,
  TError = ErrorType<unknown>,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getWeatherForecast>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getWeatherForecast>>,
          TError,
          Awaited<ReturnType<typeof getWeatherForecast>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof axiosInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetWeatherForecast<
  TData = Awaited<ReturnType<typeof getWeatherForecast>>,
  TError = ErrorType<unknown>,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getWeatherForecast>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof axiosInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};

export function useGetWeatherForecast<
  TData = Awaited<ReturnType<typeof getWeatherForecast>>,
  TError = ErrorType<unknown>,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getWeatherForecast>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof axiosInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getGetWeatherForecastQueryOptions(options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey;

  return query;
}
