// <auto-generated />
using System;
using JInshanBodyShopApi;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace JInshanBodyShopApi.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250824065200_Init6")]
    partial class Init6
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("JInshanBodyShopApi.Models.AdditionalProductInfo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Information")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.Property<string>("InformationName")
                        .IsRequired()
                        .HasColumnType("varchar(25)");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.ToTable("AdditionalProductInfos", (string)null);
                });

            modelBuilder.Entity("JInshanBodyShopApi.Models.CompanyOrder", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("CompanyName")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.Property<string>("CompanyNip")
                        .IsRequired()
                        .HasColumnType("varchar(10)");

                    b.Property<string>("ContactNumber")
                        .IsRequired()
                        .HasColumnType("varchar(9)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("date");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.Property<ulong>("Number")
                        .HasColumnType("BIGINT UNSIGNED");

                    b.Property<string>("OrderAddress")
                        .IsRequired()
                        .HasColumnType("varchar(60)");

                    b.Property<string>("OrderCity")
                        .IsRequired()
                        .HasColumnType("varchar(60)");

                    b.Property<string>("OrderCountry")
                        .IsRequired()
                        .HasColumnType("varchar(30)");

                    b.Property<string>("OrderPostalCode")
                        .IsRequired()
                        .HasColumnType("varchar(6)");

                    b.Property<string>("OrderState")
                        .IsRequired()
                        .HasColumnType("varchar(30)");

                    b.Property<string>("ShippingAddress")
                        .IsRequired()
                        .HasColumnType("varchar(60)");

                    b.Property<string>("ShippingCity")
                        .IsRequired()
                        .HasColumnType("varchar(60)");

                    b.Property<string>("ShippingCountry")
                        .IsRequired()
                        .HasColumnType("varchar(30)");

                    b.Property<string>("ShippingName")
                        .IsRequired()
                        .HasColumnType("varchar(30)");

                    b.Property<string>("ShippingOption")
                        .IsRequired()
                        .HasColumnType("varchar(10)");

                    b.Property<string>("ShippingPostalCode")
                        .IsRequired()
                        .HasColumnType("varchar(6)");

                    b.Property<string>("ShippingState")
                        .IsRequired()
                        .HasColumnType("varchar(30)");

                    b.Property<string>("ShippingSurname")
                        .IsRequired()
                        .HasColumnType("varchar(60)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("CompanyOrders", (string)null);
                });

            modelBuilder.Entity("JInshanBodyShopApi.Models.PersonalOrder", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("ContactNumber")
                        .IsRequired()
                        .HasColumnType("varchar(9)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("date");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.Property<ulong>("Number")
                        .HasColumnType("BIGINT UNSIGNED");

                    b.Property<string>("OrderAddress")
                        .IsRequired()
                        .HasColumnType("varchar(60)");

                    b.Property<string>("OrderCity")
                        .IsRequired()
                        .HasColumnType("varchar(60)");

                    b.Property<string>("OrderCountry")
                        .IsRequired()
                        .HasColumnType("varchar(30)");

                    b.Property<string>("OrderName")
                        .IsRequired()
                        .HasColumnType("varchar(30)");

                    b.Property<string>("OrderPostalCode")
                        .IsRequired()
                        .HasColumnType("varchar(6)");

                    b.Property<string>("OrderState")
                        .IsRequired()
                        .HasColumnType("varchar(30)");

                    b.Property<string>("OrderSurname")
                        .IsRequired()
                        .HasColumnType("varchar(60)");

                    b.Property<string>("ShippingAddress")
                        .IsRequired()
                        .HasColumnType("varchar(60)");

                    b.Property<string>("ShippingCity")
                        .IsRequired()
                        .HasColumnType("varchar(60)");

                    b.Property<string>("ShippingCountry")
                        .IsRequired()
                        .HasColumnType("varchar(30)");

                    b.Property<string>("ShippingName")
                        .IsRequired()
                        .HasColumnType("varchar(30)");

                    b.Property<string>("ShippingOption")
                        .IsRequired()
                        .HasColumnType("varchar(10)");

                    b.Property<string>("ShippingPostalCode")
                        .IsRequired()
                        .HasColumnType("varchar(6)");

                    b.Property<string>("ShippingState")
                        .IsRequired()
                        .HasColumnType("varchar(30)");

                    b.Property<string>("ShippingSurname")
                        .IsRequired()
                        .HasColumnType("varchar(60)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("PersonalOrders", (string)null);
                });

            modelBuilder.Entity("JInshanBodyShopApi.Models.Product", b =>
                {
                    b.Property<Guid>("ProductId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("char(36)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("varchar(400)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(25)");

                    b.Property<decimal>("Price")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<uint>("Quantity")
                        .HasColumnType("int unsigned");

                    b.Property<decimal>("Weight")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<bool>("Withdrawn")
                        .HasColumnType("tinyint(1)");

                    b.HasKey("ProductId");

                    b.ToTable("Products", (string)null);
                });

            modelBuilder.Entity("JInshanBodyShopApi.Models.SimilarProducts", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("SimilarProductId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.ToTable("SimilarProducts", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
