/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * JInshanBodyShopApi
 * OpenAPI spec version: 1.0
 */
import { useMutation, useQuery } from "@tanstack/react-query";
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult,
} from "@tanstack/react-query";

import type {
  AdditionalProductInfo,
  DeleteAdditionalInformationParams,
  GetGetAdditionalInformationParams,
  PostAdditionalInformationParams,
  PutAdditionalInformationParams,
} from "../jInshanBodyShopApi.schemas";

import { axiosInstance } from ".././axiosInstance";
import type { ErrorType } from ".././axiosInstance";

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];

export const getGetAdditionalInformation = (
  params?: GetGetAdditionalInformationParams,
  options?: SecondParameter<typeof axiosInstance>,
  signal?: AbortSignal,
) => {
  return axiosInstance<AdditionalProductInfo[]>(
    {
      url: `https://localhost:7035/GetAdditionalInformation`,
      method: "GET",
      params,
      signal,
    },
    options,
  );
};

export const getGetGetAdditionalInformationQueryKey = (
  params?: GetGetAdditionalInformationParams,
) => {
  return [
    `https://localhost:7035/GetAdditionalInformation`,
    ...(params ? [params] : []),
  ] as const;
};

export const getGetGetAdditionalInformationQueryOptions = <
  TData = Awaited<ReturnType<typeof getGetAdditionalInformation>>,
  TError = ErrorType<unknown>,
>(
  params?: GetGetAdditionalInformationParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getGetAdditionalInformation>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof axiosInstance>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ?? getGetGetAdditionalInformationQueryKey(params);

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof getGetAdditionalInformation>>
  > = ({ signal }) =>
    getGetAdditionalInformation(params, requestOptions, signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getGetAdditionalInformation>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetGetAdditionalInformationQueryResult = NonNullable<
  Awaited<ReturnType<typeof getGetAdditionalInformation>>
>;
export type GetGetAdditionalInformationQueryError = ErrorType<unknown>;

export function useGetGetAdditionalInformation<
  TData = Awaited<ReturnType<typeof getGetAdditionalInformation>>,
  TError = ErrorType<unknown>,
>(
  params: undefined | GetGetAdditionalInformationParams,
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getGetAdditionalInformation>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getGetAdditionalInformation>>,
          TError,
          Awaited<ReturnType<typeof getGetAdditionalInformation>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof axiosInstance>;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetGetAdditionalInformation<
  TData = Awaited<ReturnType<typeof getGetAdditionalInformation>>,
  TError = ErrorType<unknown>,
>(
  params?: GetGetAdditionalInformationParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getGetAdditionalInformation>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getGetAdditionalInformation>>,
          TError,
          Awaited<ReturnType<typeof getGetAdditionalInformation>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof axiosInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetGetAdditionalInformation<
  TData = Awaited<ReturnType<typeof getGetAdditionalInformation>>,
  TError = ErrorType<unknown>,
>(
  params?: GetGetAdditionalInformationParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getGetAdditionalInformation>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof axiosInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};

export function useGetGetAdditionalInformation<
  TData = Awaited<ReturnType<typeof getGetAdditionalInformation>>,
  TError = ErrorType<unknown>,
>(
  params?: GetGetAdditionalInformationParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getGetAdditionalInformation>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof axiosInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getGetGetAdditionalInformationQueryOptions(
    params,
    options,
  );

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey;

  return query;
}

export const postAdditionalInformation = (
  params?: PostAdditionalInformationParams,
  options?: SecondParameter<typeof axiosInstance>,
  signal?: AbortSignal,
) => {
  return axiosInstance<null>(
    {
      url: `https://localhost:7035/AdditionalInformation`,
      method: "POST",
      params,
      signal,
    },
    options,
  );
};

export const getPostAdditionalInformationMutationOptions = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof postAdditionalInformation>>,
    TError,
    { params?: PostAdditionalInformationParams },
    TContext
  >;
  request?: SecondParameter<typeof axiosInstance>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof postAdditionalInformation>>,
  TError,
  { params?: PostAdditionalInformationParams },
  TContext
> => {
  const mutationKey = ["postAdditionalInformation"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof postAdditionalInformation>>,
    { params?: PostAdditionalInformationParams }
  > = (props) => {
    const { params } = props ?? {};

    return postAdditionalInformation(params, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type PostAdditionalInformationMutationResult = NonNullable<
  Awaited<ReturnType<typeof postAdditionalInformation>>
>;

export type PostAdditionalInformationMutationError = ErrorType<unknown>;

export const usePostAdditionalInformation = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof postAdditionalInformation>>,
      TError,
      { params?: PostAdditionalInformationParams },
      TContext
    >;
    request?: SecondParameter<typeof axiosInstance>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof postAdditionalInformation>>,
  TError,
  { params?: PostAdditionalInformationParams },
  TContext
> => {
  const mutationOptions = getPostAdditionalInformationMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
export const putAdditionalInformation = (
  params?: PutAdditionalInformationParams,
  options?: SecondParameter<typeof axiosInstance>,
) => {
  return axiosInstance<null>(
    {
      url: `https://localhost:7035/AdditionalInformation`,
      method: "PUT",
      params,
    },
    options,
  );
};

export const getPutAdditionalInformationMutationOptions = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof putAdditionalInformation>>,
    TError,
    { params?: PutAdditionalInformationParams },
    TContext
  >;
  request?: SecondParameter<typeof axiosInstance>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof putAdditionalInformation>>,
  TError,
  { params?: PutAdditionalInformationParams },
  TContext
> => {
  const mutationKey = ["putAdditionalInformation"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof putAdditionalInformation>>,
    { params?: PutAdditionalInformationParams }
  > = (props) => {
    const { params } = props ?? {};

    return putAdditionalInformation(params, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type PutAdditionalInformationMutationResult = NonNullable<
  Awaited<ReturnType<typeof putAdditionalInformation>>
>;

export type PutAdditionalInformationMutationError = ErrorType<unknown>;

export const usePutAdditionalInformation = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof putAdditionalInformation>>,
      TError,
      { params?: PutAdditionalInformationParams },
      TContext
    >;
    request?: SecondParameter<typeof axiosInstance>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof putAdditionalInformation>>,
  TError,
  { params?: PutAdditionalInformationParams },
  TContext
> => {
  const mutationOptions = getPutAdditionalInformationMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
export const deleteAdditionalInformation = (
  params?: DeleteAdditionalInformationParams,
  options?: SecondParameter<typeof axiosInstance>,
) => {
  return axiosInstance<null>(
    {
      url: `https://localhost:7035/AdditionalInformation`,
      method: "DELETE",
      params,
    },
    options,
  );
};

export const getDeleteAdditionalInformationMutationOptions = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof deleteAdditionalInformation>>,
    TError,
    { params?: DeleteAdditionalInformationParams },
    TContext
  >;
  request?: SecondParameter<typeof axiosInstance>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof deleteAdditionalInformation>>,
  TError,
  { params?: DeleteAdditionalInformationParams },
  TContext
> => {
  const mutationKey = ["deleteAdditionalInformation"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof deleteAdditionalInformation>>,
    { params?: DeleteAdditionalInformationParams }
  > = (props) => {
    const { params } = props ?? {};

    return deleteAdditionalInformation(params, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type DeleteAdditionalInformationMutationResult = NonNullable<
  Awaited<ReturnType<typeof deleteAdditionalInformation>>
>;

export type DeleteAdditionalInformationMutationError = ErrorType<unknown>;

export const useDeleteAdditionalInformation = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof deleteAdditionalInformation>>,
      TError,
      { params?: DeleteAdditionalInformationParams },
      TContext
    >;
    request?: SecondParameter<typeof axiosInstance>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof deleteAdditionalInformation>>,
  TError,
  { params?: DeleteAdditionalInformationParams },
  TContext
> => {
  const mutationOptions =
    getDeleteAdditionalInformationMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
