/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * JInshanBodyShopApi
 * OpenAPI spec version: 1.0
 */
import { useMutation, useQuery } from "@tanstack/react-query";
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult,
} from "@tanstack/react-query";

import type {
  DeleteDeleteSimilarProductsParams,
  GetGetSimilarProductsParams,
  PostSimilarProducts,
} from "../jInshanBodyShopApi.schemas";

import { axiosInstance } from ".././axiosInstance";
import type { ErrorType, BodyType } from ".././axiosInstance";

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];

export const getGetSimilarProducts = (
  params?: GetGetSimilarProductsParams,
  options?: SecondParameter<typeof axiosInstance>,
  signal?: AbortSignal,
) => {
  return axiosInstance<null>(
    {
      url: `https://localhost:7035/GetSimilarProducts`,
      method: "GET",
      params,
      signal,
    },
    options,
  );
};

export const getGetGetSimilarProductsQueryKey = (
  params?: GetGetSimilarProductsParams,
) => {
  return [
    `https://localhost:7035/GetSimilarProducts`,
    ...(params ? [params] : []),
  ] as const;
};

export const getGetGetSimilarProductsQueryOptions = <
  TData = Awaited<ReturnType<typeof getGetSimilarProducts>>,
  TError = ErrorType<unknown>,
>(
  params?: GetGetSimilarProductsParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getGetSimilarProducts>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof axiosInstance>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ?? getGetGetSimilarProductsQueryKey(params);

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof getGetSimilarProducts>>
  > = ({ signal }) => getGetSimilarProducts(params, requestOptions, signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getGetSimilarProducts>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetGetSimilarProductsQueryResult = NonNullable<
  Awaited<ReturnType<typeof getGetSimilarProducts>>
>;
export type GetGetSimilarProductsQueryError = ErrorType<unknown>;

export function useGetGetSimilarProducts<
  TData = Awaited<ReturnType<typeof getGetSimilarProducts>>,
  TError = ErrorType<unknown>,
>(
  params: undefined | GetGetSimilarProductsParams,
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getGetSimilarProducts>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getGetSimilarProducts>>,
          TError,
          Awaited<ReturnType<typeof getGetSimilarProducts>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof axiosInstance>;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetGetSimilarProducts<
  TData = Awaited<ReturnType<typeof getGetSimilarProducts>>,
  TError = ErrorType<unknown>,
>(
  params?: GetGetSimilarProductsParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getGetSimilarProducts>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getGetSimilarProducts>>,
          TError,
          Awaited<ReturnType<typeof getGetSimilarProducts>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof axiosInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetGetSimilarProducts<
  TData = Awaited<ReturnType<typeof getGetSimilarProducts>>,
  TError = ErrorType<unknown>,
>(
  params?: GetGetSimilarProductsParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getGetSimilarProducts>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof axiosInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};

export function useGetGetSimilarProducts<
  TData = Awaited<ReturnType<typeof getGetSimilarProducts>>,
  TError = ErrorType<unknown>,
>(
  params?: GetGetSimilarProductsParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getGetSimilarProducts>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof axiosInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getGetGetSimilarProductsQueryOptions(params, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey;

  return query;
}

export const postSimilarProducts = (
  postSimilarProducts: BodyType<PostSimilarProducts>,
  options?: SecondParameter<typeof axiosInstance>,
  signal?: AbortSignal,
) => {
  return axiosInstance<null>(
    {
      url: `https://localhost:7035/SimilarProducts`,
      method: "POST",
      headers: { "Content-Type": "application/json" },
      data: postSimilarProducts,
      signal,
    },
    options,
  );
};

export const getPostSimilarProductsMutationOptions = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof postSimilarProducts>>,
    TError,
    { data: BodyType<PostSimilarProducts> },
    TContext
  >;
  request?: SecondParameter<typeof axiosInstance>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof postSimilarProducts>>,
  TError,
  { data: BodyType<PostSimilarProducts> },
  TContext
> => {
  const mutationKey = ["postSimilarProducts"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof postSimilarProducts>>,
    { data: BodyType<PostSimilarProducts> }
  > = (props) => {
    const { data } = props ?? {};

    return postSimilarProducts(data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type PostSimilarProductsMutationResult = NonNullable<
  Awaited<ReturnType<typeof postSimilarProducts>>
>;
export type PostSimilarProductsMutationBody = BodyType<PostSimilarProducts>;
export type PostSimilarProductsMutationError = ErrorType<unknown>;

export const usePostSimilarProducts = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof postSimilarProducts>>,
      TError,
      { data: BodyType<PostSimilarProducts> },
      TContext
    >;
    request?: SecondParameter<typeof axiosInstance>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof postSimilarProducts>>,
  TError,
  { data: BodyType<PostSimilarProducts> },
  TContext
> => {
  const mutationOptions = getPostSimilarProductsMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
export const deleteDeleteSimilarProducts = (
  params?: DeleteDeleteSimilarProductsParams,
  options?: SecondParameter<typeof axiosInstance>,
) => {
  return axiosInstance<null>(
    {
      url: `https://localhost:7035/DeleteSimilarProducts`,
      method: "DELETE",
      params,
    },
    options,
  );
};

export const getDeleteDeleteSimilarProductsMutationOptions = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof deleteDeleteSimilarProducts>>,
    TError,
    { params?: DeleteDeleteSimilarProductsParams },
    TContext
  >;
  request?: SecondParameter<typeof axiosInstance>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof deleteDeleteSimilarProducts>>,
  TError,
  { params?: DeleteDeleteSimilarProductsParams },
  TContext
> => {
  const mutationKey = ["deleteDeleteSimilarProducts"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof deleteDeleteSimilarProducts>>,
    { params?: DeleteDeleteSimilarProductsParams }
  > = (props) => {
    const { params } = props ?? {};

    return deleteDeleteSimilarProducts(params, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type DeleteDeleteSimilarProductsMutationResult = NonNullable<
  Awaited<ReturnType<typeof deleteDeleteSimilarProducts>>
>;

export type DeleteDeleteSimilarProductsMutationError = ErrorType<unknown>;

export const useDeleteDeleteSimilarProducts = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof deleteDeleteSimilarProducts>>,
      TError,
      { params?: DeleteDeleteSimilarProductsParams },
      TContext
    >;
    request?: SecondParameter<typeof axiosInstance>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof deleteDeleteSimilarProducts>>,
  TError,
  { params?: DeleteDeleteSimilarProductsParams },
  TContext
> => {
  const mutationOptions =
    getDeleteDeleteSimilarProductsMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
