/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * JInshanBodyShopApi
 * OpenAPI spec version: 1.0
 */
import { useMutation, useQuery } from "@tanstack/react-query";
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult,
} from "@tanstack/react-query";

import type {
  DeleteProductParams,
  GetGetProductsByIdsParams,
  GetGetProductsParams,
  GetProductParams,
  PostProduct,
  Product,
  ProductApiGetReturnType,
  PutProductParams,
} from "../jInshanBodyShopApi.schemas";

import { axiosInstance } from ".././axiosInstance";
import type { ErrorType, BodyType } from ".././axiosInstance";

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];

export const getGetProductsByIds = (
  params?: GetGetProductsByIdsParams,
  options?: SecondParameter<typeof axiosInstance>,
  signal?: AbortSignal,
) => {
  return axiosInstance<Product[]>(
    {
      url: `https://localhost:7035/GetProductsByIds`,
      method: "GET",
      params,
      signal,
    },
    options,
  );
};

export const getGetGetProductsByIdsQueryKey = (
  params?: GetGetProductsByIdsParams,
) => {
  return [
    `https://localhost:7035/GetProductsByIds`,
    ...(params ? [params] : []),
  ] as const;
};

export const getGetGetProductsByIdsQueryOptions = <
  TData = Awaited<ReturnType<typeof getGetProductsByIds>>,
  TError = ErrorType<unknown>,
>(
  params?: GetGetProductsByIdsParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getGetProductsByIds>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof axiosInstance>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ?? getGetGetProductsByIdsQueryKey(params);

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof getGetProductsByIds>>
  > = ({ signal }) => getGetProductsByIds(params, requestOptions, signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getGetProductsByIds>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetGetProductsByIdsQueryResult = NonNullable<
  Awaited<ReturnType<typeof getGetProductsByIds>>
>;
export type GetGetProductsByIdsQueryError = ErrorType<unknown>;

export function useGetGetProductsByIds<
  TData = Awaited<ReturnType<typeof getGetProductsByIds>>,
  TError = ErrorType<unknown>,
>(
  params: undefined | GetGetProductsByIdsParams,
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getGetProductsByIds>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getGetProductsByIds>>,
          TError,
          Awaited<ReturnType<typeof getGetProductsByIds>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof axiosInstance>;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetGetProductsByIds<
  TData = Awaited<ReturnType<typeof getGetProductsByIds>>,
  TError = ErrorType<unknown>,
>(
  params?: GetGetProductsByIdsParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getGetProductsByIds>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getGetProductsByIds>>,
          TError,
          Awaited<ReturnType<typeof getGetProductsByIds>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof axiosInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetGetProductsByIds<
  TData = Awaited<ReturnType<typeof getGetProductsByIds>>,
  TError = ErrorType<unknown>,
>(
  params?: GetGetProductsByIdsParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getGetProductsByIds>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof axiosInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};

export function useGetGetProductsByIds<
  TData = Awaited<ReturnType<typeof getGetProductsByIds>>,
  TError = ErrorType<unknown>,
>(
  params?: GetGetProductsByIdsParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getGetProductsByIds>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof axiosInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getGetGetProductsByIdsQueryOptions(params, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey;

  return query;
}

export const getGetProducts = (
  params?: GetGetProductsParams,
  options?: SecondParameter<typeof axiosInstance>,
  signal?: AbortSignal,
) => {
  return axiosInstance<ProductApiGetReturnType>(
    {
      url: `https://localhost:7035/GetProducts`,
      method: "GET",
      params,
      signal,
    },
    options,
  );
};

export const getGetGetProductsQueryKey = (params?: GetGetProductsParams) => {
  return [
    `https://localhost:7035/GetProducts`,
    ...(params ? [params] : []),
  ] as const;
};

export const getGetGetProductsQueryOptions = <
  TData = Awaited<ReturnType<typeof getGetProducts>>,
  TError = ErrorType<unknown>,
>(
  params?: GetGetProductsParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getGetProducts>>, TError, TData>
    >;
    request?: SecondParameter<typeof axiosInstance>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetGetProductsQueryKey(params);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getGetProducts>>> = ({
    signal,
  }) => getGetProducts(params, requestOptions, signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getGetProducts>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetGetProductsQueryResult = NonNullable<
  Awaited<ReturnType<typeof getGetProducts>>
>;
export type GetGetProductsQueryError = ErrorType<unknown>;

export function useGetGetProducts<
  TData = Awaited<ReturnType<typeof getGetProducts>>,
  TError = ErrorType<unknown>,
>(
  params: undefined | GetGetProductsParams,
  options: {
    query: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getGetProducts>>, TError, TData>
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getGetProducts>>,
          TError,
          Awaited<ReturnType<typeof getGetProducts>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof axiosInstance>;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetGetProducts<
  TData = Awaited<ReturnType<typeof getGetProducts>>,
  TError = ErrorType<unknown>,
>(
  params?: GetGetProductsParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getGetProducts>>, TError, TData>
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getGetProducts>>,
          TError,
          Awaited<ReturnType<typeof getGetProducts>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof axiosInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetGetProducts<
  TData = Awaited<ReturnType<typeof getGetProducts>>,
  TError = ErrorType<unknown>,
>(
  params?: GetGetProductsParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getGetProducts>>, TError, TData>
    >;
    request?: SecondParameter<typeof axiosInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};

export function useGetGetProducts<
  TData = Awaited<ReturnType<typeof getGetProducts>>,
  TError = ErrorType<unknown>,
>(
  params?: GetGetProductsParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getGetProducts>>, TError, TData>
    >;
    request?: SecondParameter<typeof axiosInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getGetGetProductsQueryOptions(params, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey;

  return query;
}

export const getProduct = (
  params?: GetProductParams,
  options?: SecondParameter<typeof axiosInstance>,
  signal?: AbortSignal,
) => {
  return axiosInstance<Product>(
    { url: `https://localhost:7035/Product`, method: "GET", params, signal },
    options,
  );
};

export const getGetProductQueryKey = (params?: GetProductParams) => {
  return [
    `https://localhost:7035/Product`,
    ...(params ? [params] : []),
  ] as const;
};

export const getGetProductQueryOptions = <
  TData = Awaited<ReturnType<typeof getProduct>>,
  TError = ErrorType<unknown>,
>(
  params?: GetProductParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getProduct>>, TError, TData>
    >;
    request?: SecondParameter<typeof axiosInstance>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetProductQueryKey(params);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getProduct>>> = ({
    signal,
  }) => getProduct(params, requestOptions, signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getProduct>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetProductQueryResult = NonNullable<
  Awaited<ReturnType<typeof getProduct>>
>;
export type GetProductQueryError = ErrorType<unknown>;

export function useGetProduct<
  TData = Awaited<ReturnType<typeof getProduct>>,
  TError = ErrorType<unknown>,
>(
  params: undefined | GetProductParams,
  options: {
    query: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getProduct>>, TError, TData>
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getProduct>>,
          TError,
          Awaited<ReturnType<typeof getProduct>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof axiosInstance>;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetProduct<
  TData = Awaited<ReturnType<typeof getProduct>>,
  TError = ErrorType<unknown>,
>(
  params?: GetProductParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getProduct>>, TError, TData>
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getProduct>>,
          TError,
          Awaited<ReturnType<typeof getProduct>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof axiosInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetProduct<
  TData = Awaited<ReturnType<typeof getProduct>>,
  TError = ErrorType<unknown>,
>(
  params?: GetProductParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getProduct>>, TError, TData>
    >;
    request?: SecondParameter<typeof axiosInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};

export function useGetProduct<
  TData = Awaited<ReturnType<typeof getProduct>>,
  TError = ErrorType<unknown>,
>(
  params?: GetProductParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getProduct>>, TError, TData>
    >;
    request?: SecondParameter<typeof axiosInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getGetProductQueryOptions(params, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey;

  return query;
}

export const postProduct = (
  postProduct: BodyType<PostProduct>,
  options?: SecondParameter<typeof axiosInstance>,
  signal?: AbortSignal,
) => {
  return axiosInstance<string>(
    {
      url: `https://localhost:7035/Product`,
      method: "POST",
      headers: { "Content-Type": "application/json" },
      data: postProduct,
      signal,
    },
    options,
  );
};

export const getPostProductMutationOptions = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof postProduct>>,
    TError,
    { data: BodyType<PostProduct> },
    TContext
  >;
  request?: SecondParameter<typeof axiosInstance>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof postProduct>>,
  TError,
  { data: BodyType<PostProduct> },
  TContext
> => {
  const mutationKey = ["postProduct"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof postProduct>>,
    { data: BodyType<PostProduct> }
  > = (props) => {
    const { data } = props ?? {};

    return postProduct(data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type PostProductMutationResult = NonNullable<
  Awaited<ReturnType<typeof postProduct>>
>;
export type PostProductMutationBody = BodyType<PostProduct>;
export type PostProductMutationError = ErrorType<unknown>;

export const usePostProduct = <TError = ErrorType<unknown>, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof postProduct>>,
      TError,
      { data: BodyType<PostProduct> },
      TContext
    >;
    request?: SecondParameter<typeof axiosInstance>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof postProduct>>,
  TError,
  { data: BodyType<PostProduct> },
  TContext
> => {
  const mutationOptions = getPostProductMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
export const putProduct = (
  postProduct: BodyType<PostProduct>,
  params?: PutProductParams,
  options?: SecondParameter<typeof axiosInstance>,
) => {
  return axiosInstance<null>(
    {
      url: `https://localhost:7035/Product`,
      method: "PUT",
      headers: { "Content-Type": "application/json" },
      data: postProduct,
      params,
    },
    options,
  );
};

export const getPutProductMutationOptions = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof putProduct>>,
    TError,
    { data: BodyType<PostProduct>; params?: PutProductParams },
    TContext
  >;
  request?: SecondParameter<typeof axiosInstance>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof putProduct>>,
  TError,
  { data: BodyType<PostProduct>; params?: PutProductParams },
  TContext
> => {
  const mutationKey = ["putProduct"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof putProduct>>,
    { data: BodyType<PostProduct>; params?: PutProductParams }
  > = (props) => {
    const { data, params } = props ?? {};

    return putProduct(data, params, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type PutProductMutationResult = NonNullable<
  Awaited<ReturnType<typeof putProduct>>
>;
export type PutProductMutationBody = BodyType<PostProduct>;
export type PutProductMutationError = ErrorType<unknown>;

export const usePutProduct = <TError = ErrorType<unknown>, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof putProduct>>,
      TError,
      { data: BodyType<PostProduct>; params?: PutProductParams },
      TContext
    >;
    request?: SecondParameter<typeof axiosInstance>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof putProduct>>,
  TError,
  { data: BodyType<PostProduct>; params?: PutProductParams },
  TContext
> => {
  const mutationOptions = getPutProductMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
export const deleteProduct = (
  params?: DeleteProductParams,
  options?: SecondParameter<typeof axiosInstance>,
) => {
  return axiosInstance<null>(
    { url: `https://localhost:7035/Product`, method: "DELETE", params },
    options,
  );
};

export const getDeleteProductMutationOptions = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof deleteProduct>>,
    TError,
    { params?: DeleteProductParams },
    TContext
  >;
  request?: SecondParameter<typeof axiosInstance>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof deleteProduct>>,
  TError,
  { params?: DeleteProductParams },
  TContext
> => {
  const mutationKey = ["deleteProduct"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof deleteProduct>>,
    { params?: DeleteProductParams }
  > = (props) => {
    const { params } = props ?? {};

    return deleteProduct(params, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type DeleteProductMutationResult = NonNullable<
  Awaited<ReturnType<typeof deleteProduct>>
>;

export type DeleteProductMutationError = ErrorType<unknown>;

export const useDeleteProduct = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof deleteProduct>>,
      TError,
      { params?: DeleteProductParams },
      TContext
    >;
    request?: SecondParameter<typeof axiosInstance>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof deleteProduct>>,
  TError,
  { params?: DeleteProductParams },
  TContext
> => {
  const mutationOptions = getDeleteProductMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
