/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * JInshanBodyShopApi
 * OpenAPI spec version: 1.0
 */
export interface AdditionalProductInfo {
  id?: string;
  productId?: string;
  /** @nullable */
  information: string | null;
  /** @nullable */
  informationName: string | null;
}

export interface CompanyOrder {
  orderId?: string;
  /** @nullable */
  email: string | null;
  /** @nullable */
  contactNumber: string | null;
  /** @nullable */
  orderCountry: string | null;
  /** @nullable */
  orderState: string | null;
  /** @nullable */
  orderAddress: string | null;
  /** @nullable */
  orderCity: string | null;
  /** @nullable */
  orderPostalCode: string | null;
  /** @nullable */
  shippingCountry: string | null;
  /** @nullable */
  shippingState: string | null;
  /** @nullable */
  shippingAddress: string | null;
  /** @nullable */
  shippingCity: string | null;
  /** @nullable */
  shippingPostalCode: string | null;
  /** @nullable */
  shippingName: string | null;
  /** @nullable */
  shippingSurname: string | null;
  /** @nullable */
  shippingOption: string | null;
  createdAt?: string;
  status?: OrderStatus;
  number?: number;
  orderValue: number;
  /** @nullable */
  companyName: string | null;
  /** @nullable */
  companyNip: string | null;
}

export interface CompanyOrderApiGetReturnType {
  maxPages?: number;
  /** @nullable */
  items: CompanyOrder[] | null;
}

export type OrderStatus = (typeof OrderStatus)[keyof typeof OrderStatus];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const OrderStatus = {
  NUMBER_0: 0,
  NUMBER_1: 1,
  NUMBER_2: 2,
  NUMBER_3: 3,
  NUMBER_4: 4,
  NUMBER_5: 5,
} as const;

export interface PersonalOrder {
  orderId?: string;
  /** @nullable */
  email: string | null;
  /** @nullable */
  contactNumber: string | null;
  /** @nullable */
  orderCountry: string | null;
  /** @nullable */
  orderState: string | null;
  /** @nullable */
  orderAddress: string | null;
  /** @nullable */
  orderCity: string | null;
  /** @nullable */
  orderPostalCode: string | null;
  /** @nullable */
  shippingCountry: string | null;
  /** @nullable */
  shippingState: string | null;
  /** @nullable */
  shippingAddress: string | null;
  /** @nullable */
  shippingCity: string | null;
  /** @nullable */
  shippingPostalCode: string | null;
  /** @nullable */
  shippingName: string | null;
  /** @nullable */
  shippingSurname: string | null;
  /** @nullable */
  shippingOption: string | null;
  createdAt?: string;
  status?: OrderStatus;
  number?: number;
  orderValue: number;
  /** @nullable */
  orderName: string | null;
  /** @nullable */
  orderSurname: string | null;
}

export interface PersonalOrderApiGetReturnType {
  maxPages?: number;
  /** @nullable */
  items: PersonalOrder[] | null;
}

export interface PostCompanyOrder {
  /** @nullable */
  email: string | null;
  /** @nullable */
  contactNumber: string | null;
  /** @nullable */
  orderCountry: string | null;
  /** @nullable */
  orderState: string | null;
  /** @nullable */
  orderAddress: string | null;
  /** @nullable */
  orderCity: string | null;
  /** @nullable */
  orderPostalCode: string | null;
  /** @nullable */
  shippingCountry: string | null;
  /** @nullable */
  shippingState: string | null;
  /** @nullable */
  shippingAddress: string | null;
  /** @nullable */
  shippingCity: string | null;
  /** @nullable */
  shippingPostalCode: string | null;
  /** @nullable */
  shippingName: string | null;
  /** @nullable */
  shippingSurname: string | null;
  /** @nullable */
  shippingOption: string | null;
  orderValue: number;
  /** @nullable */
  orderProducts: ProductAndQuantity[] | null;
  /** @nullable */
  companyName: string | null;
  /** @nullable */
  companyNip: string | null;
}

export interface PostPersonalOrder {
  /** @nullable */
  email: string | null;
  /** @nullable */
  contactNumber: string | null;
  /** @nullable */
  orderCountry: string | null;
  /** @nullable */
  orderState: string | null;
  /** @nullable */
  orderAddress: string | null;
  /** @nullable */
  orderCity: string | null;
  /** @nullable */
  orderPostalCode: string | null;
  /** @nullable */
  shippingCountry: string | null;
  /** @nullable */
  shippingState: string | null;
  /** @nullable */
  shippingAddress: string | null;
  /** @nullable */
  shippingCity: string | null;
  /** @nullable */
  shippingPostalCode: string | null;
  /** @nullable */
  shippingName: string | null;
  /** @nullable */
  shippingSurname: string | null;
  /** @nullable */
  shippingOption: string | null;
  orderValue: number;
  /** @nullable */
  orderProducts: ProductAndQuantity[] | null;
  /** @nullable */
  orderName: string | null;
  /** @nullable */
  orderSurname: string | null;
}

export interface PostProduct {
  /** @nullable */
  name?: string | null;
  /** @nullable */
  price?: number | null;
  /** @nullable */
  description?: string | null;
  /** @nullable */
  weight?: number | null;
  /** @nullable */
  quantity?: number | null;
  /** @nullable */
  withdrawn?: boolean | null;
  category?: ProductType;
  shop?: ProductShop;
}

export interface PostSimilarProducts {
  productId?: string;
  similarProductId?: string;
}

export interface PresignRequest {
  /** @nullable */
  fileName?: string | null;
  /** @nullable */
  contentType?: string | null;
}

export interface Product {
  productId?: string;
  /** @nullable */
  name?: string | null;
  price?: number;
  /** @nullable */
  description?: string | null;
  weight?: number;
  category: ProductType;
  quantity?: number;
  withdrawn?: boolean;
  shop?: ProductShop;
}

export interface ProductAndQuantity {
  productId?: string;
  quantity?: number;
}

export interface ProductApiGetReturnType {
  maxPages?: number;
  /** @nullable */
  items: Product[] | null;
}

export type ProductShop = (typeof ProductShop)[keyof typeof ProductShop];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ProductShop = {
  NUMBER_0: 0,
  NUMBER_1: 1,
  NUMBER_2: 2,
} as const;

export type ProductType = (typeof ProductType)[keyof typeof ProductType];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ProductType = {
  NUMBER_0: 0,
  NUMBER_1: 1,
  NUMBER_2: 2,
  NUMBER_3: 3,
  NUMBER_4: 4,
  NUMBER_5: 5,
  NUMBER_6: 6,
  NUMBER_7: 7,
} as const;

export interface WeatherForecast {
  date?: string;
  temperatureC?: number;
  readonly temperatureF?: number;
  /** @nullable */
  summary?: string | null;
}

export type GetGetAdditionalInformationParams = {
  productId?: string;
};

export type PostAdditionalInformationParams = {
  productId?: string;
  name?: string;
  information?: string;
};

export type PutAdditionalInformationParams = {
  informationId?: string;
  name?: string;
  information?: string;
};

export type DeleteAdditionalInformationParams = {
  infoId?: string;
};

export type GetPersonalProductsParams = {
  orderId?: string;
};

export type GetCompanyProductsParams = {
  orderId?: string;
};

export type GetGetOrdersPersonalParams = {
  page?: number;
  pageSize?: number;
  orderByColumn?: string;
  orderAscending?: boolean;
  orderByStatus?: OrderStatus[];
};

export type GetGetOrdersCompanyParams = {
  page?: number;
  pageSize?: number;
  orderByColumn?: string;
  orderAscending?: boolean;
  orderByStatus?: OrderStatus[];
};

export type GetGetOrderPersonalParams = {
  id?: string;
};

export type GetGetOrderCompanyParams = {
  id?: string;
};

export type GetGetOrderCompanyStatusParams = {
  id?: string;
  email?: string;
  number?: number;
};

export type GetGetOrderPersonalStatusParams = {
  id?: string;
  email?: string;
  number?: number;
};

export type PutPutPersonalOrderParams = {
  id?: string;
  status?: OrderStatus;
};

export type PutPutCompanyOrderParams = {
  id?: string;
  status?: OrderStatus;
};

export type GetDownloadParams = {
  key?: string;
};

export type GetGetProductsByIdsParams = {
  "productIds[]"?: string[];
};

export type GetGetProductsParams = {
  "filterByCategories[]"?: ProductType[];
  filterByWithdrawn?: boolean;
  shop?: ProductShop;
  filterByName?: string;
  orderByColumn?: string;
  orderAscending?: boolean;
  page?: number;
};

export type GetProductParams = {
  id?: string;
};

export type PutProductParams = {
  id?: string;
};

export type DeleteProductParams = {
  id?: string;
};

export type GetGetSimilarProductsParams = {
  productId?: string;
};

export type DeleteDeleteSimilarProductsParams = {
  productId?: string;
  similarProductId?: string;
};
