/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * JInshanBodyShopApi
 * OpenAPI spec version: 1.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import * as axios from 'axios';
import type {
  AxiosError,
  AxiosRequestConfig,
  AxiosResponse
} from 'axios';

import type {
  GetGetProductsParams,
  GetProductParams,
  PostProduct,
  Product,
  PutProductParams,
  WeatherForecast
} from './jInshanBodyShopApi.schemas';





export const getGetProducts = (
    params?: GetGetProductsParams, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<Product[]>> => {
    
    
    return axios.default.get(
      `/GetProducts`,{
    ...options,
        params: {...params, ...options?.params},}
    );
  }


export const getGetGetProductsQueryKey = (params?: GetGetProductsParams,) => {
    return [`/GetProducts`, ...(params ? [params]: [])] as const;
    }

    
export const getGetGetProductsQueryOptions = <TData = Awaited<ReturnType<typeof getGetProducts>>, TError = AxiosError<unknown>>(params?: GetGetProductsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getGetProducts>>, TError, TData>>, axios?: AxiosRequestConfig}
) => {

const {query: queryOptions, axios: axiosOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetGetProductsQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getGetProducts>>> = ({ signal }) => getGetProducts(params, { signal, ...axiosOptions });

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getGetProducts>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetGetProductsQueryResult = NonNullable<Awaited<ReturnType<typeof getGetProducts>>>
export type GetGetProductsQueryError = AxiosError<unknown>


export function useGetGetProducts<TData = Awaited<ReturnType<typeof getGetProducts>>, TError = AxiosError<unknown>>(
 params: undefined |  GetGetProductsParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getGetProducts>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getGetProducts>>,
          TError,
          Awaited<ReturnType<typeof getGetProducts>>
        > , 'initialData'
      >, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetGetProducts<TData = Awaited<ReturnType<typeof getGetProducts>>, TError = AxiosError<unknown>>(
 params?: GetGetProductsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getGetProducts>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getGetProducts>>,
          TError,
          Awaited<ReturnType<typeof getGetProducts>>
        > , 'initialData'
      >, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetGetProducts<TData = Awaited<ReturnType<typeof getGetProducts>>, TError = AxiosError<unknown>>(
 params?: GetGetProductsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getGetProducts>>, TError, TData>>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useGetGetProducts<TData = Awaited<ReturnType<typeof getGetProducts>>, TError = AxiosError<unknown>>(
 params?: GetGetProductsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getGetProducts>>, TError, TData>>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetGetProductsQueryOptions(params,options)

  const query = useQuery(queryOptions , queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




export const getProduct = (
    params?: GetProductParams, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<null>> => {
    
    
    return axios.default.get(
      `/Product`,{
    ...options,
        params: {...params, ...options?.params},}
    );
  }


export const getGetProductQueryKey = (params?: GetProductParams,) => {
    return [`/Product`, ...(params ? [params]: [])] as const;
    }

    
export const getGetProductQueryOptions = <TData = Awaited<ReturnType<typeof getProduct>>, TError = AxiosError<unknown>>(params?: GetProductParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getProduct>>, TError, TData>>, axios?: AxiosRequestConfig}
) => {

const {query: queryOptions, axios: axiosOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetProductQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getProduct>>> = ({ signal }) => getProduct(params, { signal, ...axiosOptions });

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getProduct>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetProductQueryResult = NonNullable<Awaited<ReturnType<typeof getProduct>>>
export type GetProductQueryError = AxiosError<unknown>


export function useGetProduct<TData = Awaited<ReturnType<typeof getProduct>>, TError = AxiosError<unknown>>(
 params: undefined |  GetProductParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getProduct>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getProduct>>,
          TError,
          Awaited<ReturnType<typeof getProduct>>
        > , 'initialData'
      >, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetProduct<TData = Awaited<ReturnType<typeof getProduct>>, TError = AxiosError<unknown>>(
 params?: GetProductParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getProduct>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getProduct>>,
          TError,
          Awaited<ReturnType<typeof getProduct>>
        > , 'initialData'
      >, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetProduct<TData = Awaited<ReturnType<typeof getProduct>>, TError = AxiosError<unknown>>(
 params?: GetProductParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getProduct>>, TError, TData>>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useGetProduct<TData = Awaited<ReturnType<typeof getProduct>>, TError = AxiosError<unknown>>(
 params?: GetProductParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getProduct>>, TError, TData>>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetProductQueryOptions(params,options)

  const query = useQuery(queryOptions , queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




export const postProduct = (
    postProduct: PostProduct, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<null>> => {
    
    
    return axios.default.post(
      `/Product`,
      postProduct,options
    );
  }



export const getPostProductMutationOptions = <TError = AxiosError<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postProduct>>, TError,{data: PostProduct}, TContext>, axios?: AxiosRequestConfig}
): UseMutationOptions<Awaited<ReturnType<typeof postProduct>>, TError,{data: PostProduct}, TContext> => {

const mutationKey = ['postProduct'];
const {mutation: mutationOptions, axios: axiosOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, axios: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postProduct>>, {data: PostProduct}> = (props) => {
          const {data} = props ?? {};

          return  postProduct(data,axiosOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type PostProductMutationResult = NonNullable<Awaited<ReturnType<typeof postProduct>>>
    export type PostProductMutationBody = PostProduct
    export type PostProductMutationError = AxiosError<unknown>

    export const usePostProduct = <TError = AxiosError<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postProduct>>, TError,{data: PostProduct}, TContext>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postProduct>>,
        TError,
        {data: PostProduct},
        TContext
      > => {

      const mutationOptions = getPostProductMutationOptions(options);

      return useMutation(mutationOptions , queryClient);
    }
    
export const putProduct = (
    postProduct: PostProduct,
    params?: PutProductParams, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<null>> => {
    
    
    return axios.default.put(
      `/Product`,
      postProduct,{
    ...options,
        params: {...params, ...options?.params},}
    );
  }



export const getPutProductMutationOptions = <TError = AxiosError<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof putProduct>>, TError,{data: PostProduct;params?: PutProductParams}, TContext>, axios?: AxiosRequestConfig}
): UseMutationOptions<Awaited<ReturnType<typeof putProduct>>, TError,{data: PostProduct;params?: PutProductParams}, TContext> => {

const mutationKey = ['putProduct'];
const {mutation: mutationOptions, axios: axiosOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, axios: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof putProduct>>, {data: PostProduct;params?: PutProductParams}> = (props) => {
          const {data,params} = props ?? {};

          return  putProduct(data,params,axiosOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type PutProductMutationResult = NonNullable<Awaited<ReturnType<typeof putProduct>>>
    export type PutProductMutationBody = PostProduct
    export type PutProductMutationError = AxiosError<unknown>

    export const usePutProduct = <TError = AxiosError<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof putProduct>>, TError,{data: PostProduct;params?: PutProductParams}, TContext>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof putProduct>>,
        TError,
        {data: PostProduct;params?: PutProductParams},
        TContext
      > => {

      const mutationOptions = getPutProductMutationOptions(options);

      return useMutation(mutationOptions , queryClient);
    }
    
export const getWeatherForecast = (
     options?: AxiosRequestConfig
 ): Promise<AxiosResponse<WeatherForecast[]>> => {
    
    
    return axios.default.get(
      `/WeatherForecast`,options
    );
  }


export const getGetWeatherForecastQueryKey = () => {
    return [`/WeatherForecast`] as const;
    }

    
export const getGetWeatherForecastQueryOptions = <TData = Awaited<ReturnType<typeof getWeatherForecast>>, TError = AxiosError<unknown>>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getWeatherForecast>>, TError, TData>>, axios?: AxiosRequestConfig}
) => {

const {query: queryOptions, axios: axiosOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetWeatherForecastQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getWeatherForecast>>> = ({ signal }) => getWeatherForecast({ signal, ...axiosOptions });

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getWeatherForecast>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetWeatherForecastQueryResult = NonNullable<Awaited<ReturnType<typeof getWeatherForecast>>>
export type GetWeatherForecastQueryError = AxiosError<unknown>


export function useGetWeatherForecast<TData = Awaited<ReturnType<typeof getWeatherForecast>>, TError = AxiosError<unknown>>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getWeatherForecast>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getWeatherForecast>>,
          TError,
          Awaited<ReturnType<typeof getWeatherForecast>>
        > , 'initialData'
      >, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetWeatherForecast<TData = Awaited<ReturnType<typeof getWeatherForecast>>, TError = AxiosError<unknown>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getWeatherForecast>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getWeatherForecast>>,
          TError,
          Awaited<ReturnType<typeof getWeatherForecast>>
        > , 'initialData'
      >, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetWeatherForecast<TData = Awaited<ReturnType<typeof getWeatherForecast>>, TError = AxiosError<unknown>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getWeatherForecast>>, TError, TData>>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useGetWeatherForecast<TData = Awaited<ReturnType<typeof getWeatherForecast>>, TError = AxiosError<unknown>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getWeatherForecast>>, TError, TData>>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetWeatherForecastQueryOptions(options)

  const query = useQuery(queryOptions , queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




