/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * JInshanBodyShopApi
 * OpenAPI spec version: 1.0
 */
import { useMutation, useQuery } from "@tanstack/react-query";
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult,
} from "@tanstack/react-query";

import type {
  CompanyOrder,
  CompanyOrderApiGetReturnType,
  GetCompanyProductsParams,
  GetGetOrderCompanyParams,
  GetGetOrderCompanyStatusParams,
  GetGetOrderPersonalParams,
  GetGetOrderPersonalStatusParams,
  GetGetOrdersCompanyParams,
  GetGetOrdersPersonalParams,
  GetPersonalProductsParams,
  PersonalOrder,
  PersonalOrderApiGetReturnType,
  PostCompanyOrder,
  PostPersonalOrder,
  Product,
  PutPutCompanyOrderParams,
  PutPutPersonalOrderParams,
} from "../jInshanBodyShopApi.schemas";

import { axiosInstance } from ".././axiosInstance";
import type { ErrorType, BodyType } from ".././axiosInstance";

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];

export const getPersonalProducts = (
  params?: GetPersonalProductsParams,
  options?: SecondParameter<typeof axiosInstance>,
  signal?: AbortSignal,
) => {
  return axiosInstance<Product[]>(
    {
      url: `https://localhost:7035/Personal/Products`,
      method: "GET",
      params,
      signal,
    },
    options,
  );
};

export const getGetPersonalProductsQueryKey = (
  params?: GetPersonalProductsParams,
) => {
  return [
    `https://localhost:7035/Personal/Products`,
    ...(params ? [params] : []),
  ] as const;
};

export const getGetPersonalProductsQueryOptions = <
  TData = Awaited<ReturnType<typeof getPersonalProducts>>,
  TError = ErrorType<unknown>,
>(
  params?: GetPersonalProductsParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getPersonalProducts>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof axiosInstance>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ?? getGetPersonalProductsQueryKey(params);

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof getPersonalProducts>>
  > = ({ signal }) => getPersonalProducts(params, requestOptions, signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getPersonalProducts>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetPersonalProductsQueryResult = NonNullable<
  Awaited<ReturnType<typeof getPersonalProducts>>
>;
export type GetPersonalProductsQueryError = ErrorType<unknown>;

export function useGetPersonalProducts<
  TData = Awaited<ReturnType<typeof getPersonalProducts>>,
  TError = ErrorType<unknown>,
>(
  params: undefined | GetPersonalProductsParams,
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getPersonalProducts>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getPersonalProducts>>,
          TError,
          Awaited<ReturnType<typeof getPersonalProducts>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof axiosInstance>;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetPersonalProducts<
  TData = Awaited<ReturnType<typeof getPersonalProducts>>,
  TError = ErrorType<unknown>,
>(
  params?: GetPersonalProductsParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getPersonalProducts>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getPersonalProducts>>,
          TError,
          Awaited<ReturnType<typeof getPersonalProducts>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof axiosInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetPersonalProducts<
  TData = Awaited<ReturnType<typeof getPersonalProducts>>,
  TError = ErrorType<unknown>,
>(
  params?: GetPersonalProductsParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getPersonalProducts>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof axiosInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};

export function useGetPersonalProducts<
  TData = Awaited<ReturnType<typeof getPersonalProducts>>,
  TError = ErrorType<unknown>,
>(
  params?: GetPersonalProductsParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getPersonalProducts>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof axiosInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getGetPersonalProductsQueryOptions(params, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey;

  return query;
}

export const getCompanyProducts = (
  params?: GetCompanyProductsParams,
  options?: SecondParameter<typeof axiosInstance>,
  signal?: AbortSignal,
) => {
  return axiosInstance<Product[]>(
    {
      url: `https://localhost:7035/Company/Products`,
      method: "GET",
      params,
      signal,
    },
    options,
  );
};

export const getGetCompanyProductsQueryKey = (
  params?: GetCompanyProductsParams,
) => {
  return [
    `https://localhost:7035/Company/Products`,
    ...(params ? [params] : []),
  ] as const;
};

export const getGetCompanyProductsQueryOptions = <
  TData = Awaited<ReturnType<typeof getCompanyProducts>>,
  TError = ErrorType<unknown>,
>(
  params?: GetCompanyProductsParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getCompanyProducts>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof axiosInstance>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ?? getGetCompanyProductsQueryKey(params);

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof getCompanyProducts>>
  > = ({ signal }) => getCompanyProducts(params, requestOptions, signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getCompanyProducts>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetCompanyProductsQueryResult = NonNullable<
  Awaited<ReturnType<typeof getCompanyProducts>>
>;
export type GetCompanyProductsQueryError = ErrorType<unknown>;

export function useGetCompanyProducts<
  TData = Awaited<ReturnType<typeof getCompanyProducts>>,
  TError = ErrorType<unknown>,
>(
  params: undefined | GetCompanyProductsParams,
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getCompanyProducts>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getCompanyProducts>>,
          TError,
          Awaited<ReturnType<typeof getCompanyProducts>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof axiosInstance>;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetCompanyProducts<
  TData = Awaited<ReturnType<typeof getCompanyProducts>>,
  TError = ErrorType<unknown>,
>(
  params?: GetCompanyProductsParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getCompanyProducts>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getCompanyProducts>>,
          TError,
          Awaited<ReturnType<typeof getCompanyProducts>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof axiosInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetCompanyProducts<
  TData = Awaited<ReturnType<typeof getCompanyProducts>>,
  TError = ErrorType<unknown>,
>(
  params?: GetCompanyProductsParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getCompanyProducts>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof axiosInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};

export function useGetCompanyProducts<
  TData = Awaited<ReturnType<typeof getCompanyProducts>>,
  TError = ErrorType<unknown>,
>(
  params?: GetCompanyProductsParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getCompanyProducts>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof axiosInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getGetCompanyProductsQueryOptions(params, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey;

  return query;
}

export const getGetOrdersPersonal = (
  params?: GetGetOrdersPersonalParams,
  options?: SecondParameter<typeof axiosInstance>,
  signal?: AbortSignal,
) => {
  return axiosInstance<PersonalOrderApiGetReturnType>(
    {
      url: `https://localhost:7035/GetOrders/Personal`,
      method: "GET",
      params,
      signal,
    },
    options,
  );
};

export const getGetGetOrdersPersonalQueryKey = (
  params?: GetGetOrdersPersonalParams,
) => {
  return [
    `https://localhost:7035/GetOrders/Personal`,
    ...(params ? [params] : []),
  ] as const;
};

export const getGetGetOrdersPersonalQueryOptions = <
  TData = Awaited<ReturnType<typeof getGetOrdersPersonal>>,
  TError = ErrorType<unknown>,
>(
  params?: GetGetOrdersPersonalParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getGetOrdersPersonal>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof axiosInstance>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ?? getGetGetOrdersPersonalQueryKey(params);

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof getGetOrdersPersonal>>
  > = ({ signal }) => getGetOrdersPersonal(params, requestOptions, signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getGetOrdersPersonal>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetGetOrdersPersonalQueryResult = NonNullable<
  Awaited<ReturnType<typeof getGetOrdersPersonal>>
>;
export type GetGetOrdersPersonalQueryError = ErrorType<unknown>;

export function useGetGetOrdersPersonal<
  TData = Awaited<ReturnType<typeof getGetOrdersPersonal>>,
  TError = ErrorType<unknown>,
>(
  params: undefined | GetGetOrdersPersonalParams,
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getGetOrdersPersonal>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getGetOrdersPersonal>>,
          TError,
          Awaited<ReturnType<typeof getGetOrdersPersonal>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof axiosInstance>;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetGetOrdersPersonal<
  TData = Awaited<ReturnType<typeof getGetOrdersPersonal>>,
  TError = ErrorType<unknown>,
>(
  params?: GetGetOrdersPersonalParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getGetOrdersPersonal>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getGetOrdersPersonal>>,
          TError,
          Awaited<ReturnType<typeof getGetOrdersPersonal>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof axiosInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetGetOrdersPersonal<
  TData = Awaited<ReturnType<typeof getGetOrdersPersonal>>,
  TError = ErrorType<unknown>,
>(
  params?: GetGetOrdersPersonalParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getGetOrdersPersonal>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof axiosInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};

export function useGetGetOrdersPersonal<
  TData = Awaited<ReturnType<typeof getGetOrdersPersonal>>,
  TError = ErrorType<unknown>,
>(
  params?: GetGetOrdersPersonalParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getGetOrdersPersonal>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof axiosInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getGetGetOrdersPersonalQueryOptions(params, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey;

  return query;
}

export const getGetOrdersCompany = (
  params?: GetGetOrdersCompanyParams,
  options?: SecondParameter<typeof axiosInstance>,
  signal?: AbortSignal,
) => {
  return axiosInstance<CompanyOrderApiGetReturnType>(
    {
      url: `https://localhost:7035/GetOrders/Company`,
      method: "GET",
      params,
      signal,
    },
    options,
  );
};

export const getGetGetOrdersCompanyQueryKey = (
  params?: GetGetOrdersCompanyParams,
) => {
  return [
    `https://localhost:7035/GetOrders/Company`,
    ...(params ? [params] : []),
  ] as const;
};

export const getGetGetOrdersCompanyQueryOptions = <
  TData = Awaited<ReturnType<typeof getGetOrdersCompany>>,
  TError = ErrorType<unknown>,
>(
  params?: GetGetOrdersCompanyParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getGetOrdersCompany>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof axiosInstance>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ?? getGetGetOrdersCompanyQueryKey(params);

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof getGetOrdersCompany>>
  > = ({ signal }) => getGetOrdersCompany(params, requestOptions, signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getGetOrdersCompany>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetGetOrdersCompanyQueryResult = NonNullable<
  Awaited<ReturnType<typeof getGetOrdersCompany>>
>;
export type GetGetOrdersCompanyQueryError = ErrorType<unknown>;

export function useGetGetOrdersCompany<
  TData = Awaited<ReturnType<typeof getGetOrdersCompany>>,
  TError = ErrorType<unknown>,
>(
  params: undefined | GetGetOrdersCompanyParams,
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getGetOrdersCompany>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getGetOrdersCompany>>,
          TError,
          Awaited<ReturnType<typeof getGetOrdersCompany>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof axiosInstance>;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetGetOrdersCompany<
  TData = Awaited<ReturnType<typeof getGetOrdersCompany>>,
  TError = ErrorType<unknown>,
>(
  params?: GetGetOrdersCompanyParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getGetOrdersCompany>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getGetOrdersCompany>>,
          TError,
          Awaited<ReturnType<typeof getGetOrdersCompany>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof axiosInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetGetOrdersCompany<
  TData = Awaited<ReturnType<typeof getGetOrdersCompany>>,
  TError = ErrorType<unknown>,
>(
  params?: GetGetOrdersCompanyParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getGetOrdersCompany>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof axiosInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};

export function useGetGetOrdersCompany<
  TData = Awaited<ReturnType<typeof getGetOrdersCompany>>,
  TError = ErrorType<unknown>,
>(
  params?: GetGetOrdersCompanyParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getGetOrdersCompany>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof axiosInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getGetGetOrdersCompanyQueryOptions(params, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey;

  return query;
}

export const getGetOrderPersonal = (
  params?: GetGetOrderPersonalParams,
  options?: SecondParameter<typeof axiosInstance>,
  signal?: AbortSignal,
) => {
  return axiosInstance<PersonalOrder>(
    {
      url: `https://localhost:7035/GetOrder/Personal`,
      method: "GET",
      params,
      signal,
    },
    options,
  );
};

export const getGetGetOrderPersonalQueryKey = (
  params?: GetGetOrderPersonalParams,
) => {
  return [
    `https://localhost:7035/GetOrder/Personal`,
    ...(params ? [params] : []),
  ] as const;
};

export const getGetGetOrderPersonalQueryOptions = <
  TData = Awaited<ReturnType<typeof getGetOrderPersonal>>,
  TError = ErrorType<unknown>,
>(
  params?: GetGetOrderPersonalParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getGetOrderPersonal>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof axiosInstance>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ?? getGetGetOrderPersonalQueryKey(params);

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof getGetOrderPersonal>>
  > = ({ signal }) => getGetOrderPersonal(params, requestOptions, signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getGetOrderPersonal>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetGetOrderPersonalQueryResult = NonNullable<
  Awaited<ReturnType<typeof getGetOrderPersonal>>
>;
export type GetGetOrderPersonalQueryError = ErrorType<unknown>;

export function useGetGetOrderPersonal<
  TData = Awaited<ReturnType<typeof getGetOrderPersonal>>,
  TError = ErrorType<unknown>,
>(
  params: undefined | GetGetOrderPersonalParams,
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getGetOrderPersonal>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getGetOrderPersonal>>,
          TError,
          Awaited<ReturnType<typeof getGetOrderPersonal>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof axiosInstance>;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetGetOrderPersonal<
  TData = Awaited<ReturnType<typeof getGetOrderPersonal>>,
  TError = ErrorType<unknown>,
>(
  params?: GetGetOrderPersonalParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getGetOrderPersonal>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getGetOrderPersonal>>,
          TError,
          Awaited<ReturnType<typeof getGetOrderPersonal>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof axiosInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetGetOrderPersonal<
  TData = Awaited<ReturnType<typeof getGetOrderPersonal>>,
  TError = ErrorType<unknown>,
>(
  params?: GetGetOrderPersonalParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getGetOrderPersonal>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof axiosInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};

export function useGetGetOrderPersonal<
  TData = Awaited<ReturnType<typeof getGetOrderPersonal>>,
  TError = ErrorType<unknown>,
>(
  params?: GetGetOrderPersonalParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getGetOrderPersonal>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof axiosInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getGetGetOrderPersonalQueryOptions(params, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey;

  return query;
}

export const getGetOrderCompany = (
  params?: GetGetOrderCompanyParams,
  options?: SecondParameter<typeof axiosInstance>,
  signal?: AbortSignal,
) => {
  return axiosInstance<CompanyOrder>(
    {
      url: `https://localhost:7035/GetOrder/Company`,
      method: "GET",
      params,
      signal,
    },
    options,
  );
};

export const getGetGetOrderCompanyQueryKey = (
  params?: GetGetOrderCompanyParams,
) => {
  return [
    `https://localhost:7035/GetOrder/Company`,
    ...(params ? [params] : []),
  ] as const;
};

export const getGetGetOrderCompanyQueryOptions = <
  TData = Awaited<ReturnType<typeof getGetOrderCompany>>,
  TError = ErrorType<unknown>,
>(
  params?: GetGetOrderCompanyParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getGetOrderCompany>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof axiosInstance>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ?? getGetGetOrderCompanyQueryKey(params);

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof getGetOrderCompany>>
  > = ({ signal }) => getGetOrderCompany(params, requestOptions, signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getGetOrderCompany>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetGetOrderCompanyQueryResult = NonNullable<
  Awaited<ReturnType<typeof getGetOrderCompany>>
>;
export type GetGetOrderCompanyQueryError = ErrorType<unknown>;

export function useGetGetOrderCompany<
  TData = Awaited<ReturnType<typeof getGetOrderCompany>>,
  TError = ErrorType<unknown>,
>(
  params: undefined | GetGetOrderCompanyParams,
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getGetOrderCompany>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getGetOrderCompany>>,
          TError,
          Awaited<ReturnType<typeof getGetOrderCompany>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof axiosInstance>;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetGetOrderCompany<
  TData = Awaited<ReturnType<typeof getGetOrderCompany>>,
  TError = ErrorType<unknown>,
>(
  params?: GetGetOrderCompanyParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getGetOrderCompany>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getGetOrderCompany>>,
          TError,
          Awaited<ReturnType<typeof getGetOrderCompany>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof axiosInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetGetOrderCompany<
  TData = Awaited<ReturnType<typeof getGetOrderCompany>>,
  TError = ErrorType<unknown>,
>(
  params?: GetGetOrderCompanyParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getGetOrderCompany>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof axiosInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};

export function useGetGetOrderCompany<
  TData = Awaited<ReturnType<typeof getGetOrderCompany>>,
  TError = ErrorType<unknown>,
>(
  params?: GetGetOrderCompanyParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getGetOrderCompany>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof axiosInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getGetGetOrderCompanyQueryOptions(params, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey;

  return query;
}

export const getGetOrderCompanyStatus = (
  params?: GetGetOrderCompanyStatusParams,
  options?: SecondParameter<typeof axiosInstance>,
  signal?: AbortSignal,
) => {
  return axiosInstance<CompanyOrder>(
    {
      url: `https://localhost:7035/GetOrder/Company/Status`,
      method: "GET",
      params,
      signal,
    },
    options,
  );
};

export const getGetGetOrderCompanyStatusQueryKey = (
  params?: GetGetOrderCompanyStatusParams,
) => {
  return [
    `https://localhost:7035/GetOrder/Company/Status`,
    ...(params ? [params] : []),
  ] as const;
};

export const getGetGetOrderCompanyStatusQueryOptions = <
  TData = Awaited<ReturnType<typeof getGetOrderCompanyStatus>>,
  TError = ErrorType<unknown>,
>(
  params?: GetGetOrderCompanyStatusParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getGetOrderCompanyStatus>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof axiosInstance>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ?? getGetGetOrderCompanyStatusQueryKey(params);

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof getGetOrderCompanyStatus>>
  > = ({ signal }) => getGetOrderCompanyStatus(params, requestOptions, signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getGetOrderCompanyStatus>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetGetOrderCompanyStatusQueryResult = NonNullable<
  Awaited<ReturnType<typeof getGetOrderCompanyStatus>>
>;
export type GetGetOrderCompanyStatusQueryError = ErrorType<unknown>;

export function useGetGetOrderCompanyStatus<
  TData = Awaited<ReturnType<typeof getGetOrderCompanyStatus>>,
  TError = ErrorType<unknown>,
>(
  params: undefined | GetGetOrderCompanyStatusParams,
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getGetOrderCompanyStatus>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getGetOrderCompanyStatus>>,
          TError,
          Awaited<ReturnType<typeof getGetOrderCompanyStatus>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof axiosInstance>;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetGetOrderCompanyStatus<
  TData = Awaited<ReturnType<typeof getGetOrderCompanyStatus>>,
  TError = ErrorType<unknown>,
>(
  params?: GetGetOrderCompanyStatusParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getGetOrderCompanyStatus>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getGetOrderCompanyStatus>>,
          TError,
          Awaited<ReturnType<typeof getGetOrderCompanyStatus>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof axiosInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetGetOrderCompanyStatus<
  TData = Awaited<ReturnType<typeof getGetOrderCompanyStatus>>,
  TError = ErrorType<unknown>,
>(
  params?: GetGetOrderCompanyStatusParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getGetOrderCompanyStatus>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof axiosInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};

export function useGetGetOrderCompanyStatus<
  TData = Awaited<ReturnType<typeof getGetOrderCompanyStatus>>,
  TError = ErrorType<unknown>,
>(
  params?: GetGetOrderCompanyStatusParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getGetOrderCompanyStatus>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof axiosInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getGetGetOrderCompanyStatusQueryOptions(params, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey;

  return query;
}

export const getGetOrderPersonalStatus = (
  params?: GetGetOrderPersonalStatusParams,
  options?: SecondParameter<typeof axiosInstance>,
  signal?: AbortSignal,
) => {
  return axiosInstance<PersonalOrder>(
    {
      url: `https://localhost:7035/GetOrder/Personal/Status`,
      method: "GET",
      params,
      signal,
    },
    options,
  );
};

export const getGetGetOrderPersonalStatusQueryKey = (
  params?: GetGetOrderPersonalStatusParams,
) => {
  return [
    `https://localhost:7035/GetOrder/Personal/Status`,
    ...(params ? [params] : []),
  ] as const;
};

export const getGetGetOrderPersonalStatusQueryOptions = <
  TData = Awaited<ReturnType<typeof getGetOrderPersonalStatus>>,
  TError = ErrorType<unknown>,
>(
  params?: GetGetOrderPersonalStatusParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getGetOrderPersonalStatus>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof axiosInstance>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ?? getGetGetOrderPersonalStatusQueryKey(params);

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof getGetOrderPersonalStatus>>
  > = ({ signal }) => getGetOrderPersonalStatus(params, requestOptions, signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getGetOrderPersonalStatus>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetGetOrderPersonalStatusQueryResult = NonNullable<
  Awaited<ReturnType<typeof getGetOrderPersonalStatus>>
>;
export type GetGetOrderPersonalStatusQueryError = ErrorType<unknown>;

export function useGetGetOrderPersonalStatus<
  TData = Awaited<ReturnType<typeof getGetOrderPersonalStatus>>,
  TError = ErrorType<unknown>,
>(
  params: undefined | GetGetOrderPersonalStatusParams,
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getGetOrderPersonalStatus>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getGetOrderPersonalStatus>>,
          TError,
          Awaited<ReturnType<typeof getGetOrderPersonalStatus>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof axiosInstance>;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetGetOrderPersonalStatus<
  TData = Awaited<ReturnType<typeof getGetOrderPersonalStatus>>,
  TError = ErrorType<unknown>,
>(
  params?: GetGetOrderPersonalStatusParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getGetOrderPersonalStatus>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getGetOrderPersonalStatus>>,
          TError,
          Awaited<ReturnType<typeof getGetOrderPersonalStatus>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof axiosInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetGetOrderPersonalStatus<
  TData = Awaited<ReturnType<typeof getGetOrderPersonalStatus>>,
  TError = ErrorType<unknown>,
>(
  params?: GetGetOrderPersonalStatusParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getGetOrderPersonalStatus>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof axiosInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};

export function useGetGetOrderPersonalStatus<
  TData = Awaited<ReturnType<typeof getGetOrderPersonalStatus>>,
  TError = ErrorType<unknown>,
>(
  params?: GetGetOrderPersonalStatusParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getGetOrderPersonalStatus>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof axiosInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getGetGetOrderPersonalStatusQueryOptions(
    params,
    options,
  );

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey;

  return query;
}

export const postPostCompanyOrder = (
  postCompanyOrder: BodyType<PostCompanyOrder>,
  options?: SecondParameter<typeof axiosInstance>,
  signal?: AbortSignal,
) => {
  return axiosInstance<string>(
    {
      url: `https://localhost:7035/PostCompanyOrder`,
      method: "POST",
      headers: { "Content-Type": "application/json" },
      data: postCompanyOrder,
      signal,
    },
    options,
  );
};

export const getPostPostCompanyOrderMutationOptions = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof postPostCompanyOrder>>,
    TError,
    { data: BodyType<PostCompanyOrder> },
    TContext
  >;
  request?: SecondParameter<typeof axiosInstance>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof postPostCompanyOrder>>,
  TError,
  { data: BodyType<PostCompanyOrder> },
  TContext
> => {
  const mutationKey = ["postPostCompanyOrder"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof postPostCompanyOrder>>,
    { data: BodyType<PostCompanyOrder> }
  > = (props) => {
    const { data } = props ?? {};

    return postPostCompanyOrder(data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type PostPostCompanyOrderMutationResult = NonNullable<
  Awaited<ReturnType<typeof postPostCompanyOrder>>
>;
export type PostPostCompanyOrderMutationBody = BodyType<PostCompanyOrder>;
export type PostPostCompanyOrderMutationError = ErrorType<unknown>;

export const usePostPostCompanyOrder = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof postPostCompanyOrder>>,
      TError,
      { data: BodyType<PostCompanyOrder> },
      TContext
    >;
    request?: SecondParameter<typeof axiosInstance>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof postPostCompanyOrder>>,
  TError,
  { data: BodyType<PostCompanyOrder> },
  TContext
> => {
  const mutationOptions = getPostPostCompanyOrderMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
export const postPostPersonalOrder = (
  postPersonalOrder: BodyType<PostPersonalOrder>,
  options?: SecondParameter<typeof axiosInstance>,
  signal?: AbortSignal,
) => {
  return axiosInstance<string>(
    {
      url: `https://localhost:7035/PostPersonalOrder`,
      method: "POST",
      headers: { "Content-Type": "application/json" },
      data: postPersonalOrder,
      signal,
    },
    options,
  );
};

export const getPostPostPersonalOrderMutationOptions = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof postPostPersonalOrder>>,
    TError,
    { data: BodyType<PostPersonalOrder> },
    TContext
  >;
  request?: SecondParameter<typeof axiosInstance>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof postPostPersonalOrder>>,
  TError,
  { data: BodyType<PostPersonalOrder> },
  TContext
> => {
  const mutationKey = ["postPostPersonalOrder"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof postPostPersonalOrder>>,
    { data: BodyType<PostPersonalOrder> }
  > = (props) => {
    const { data } = props ?? {};

    return postPostPersonalOrder(data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type PostPostPersonalOrderMutationResult = NonNullable<
  Awaited<ReturnType<typeof postPostPersonalOrder>>
>;
export type PostPostPersonalOrderMutationBody = BodyType<PostPersonalOrder>;
export type PostPostPersonalOrderMutationError = ErrorType<unknown>;

export const usePostPostPersonalOrder = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof postPostPersonalOrder>>,
      TError,
      { data: BodyType<PostPersonalOrder> },
      TContext
    >;
    request?: SecondParameter<typeof axiosInstance>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof postPostPersonalOrder>>,
  TError,
  { data: BodyType<PostPersonalOrder> },
  TContext
> => {
  const mutationOptions = getPostPostPersonalOrderMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
export const putPutPersonalOrder = (
  params?: PutPutPersonalOrderParams,
  options?: SecondParameter<typeof axiosInstance>,
) => {
  return axiosInstance<null>(
    { url: `https://localhost:7035/PutPersonalOrder`, method: "PUT", params },
    options,
  );
};

export const getPutPutPersonalOrderMutationOptions = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof putPutPersonalOrder>>,
    TError,
    { params?: PutPutPersonalOrderParams },
    TContext
  >;
  request?: SecondParameter<typeof axiosInstance>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof putPutPersonalOrder>>,
  TError,
  { params?: PutPutPersonalOrderParams },
  TContext
> => {
  const mutationKey = ["putPutPersonalOrder"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof putPutPersonalOrder>>,
    { params?: PutPutPersonalOrderParams }
  > = (props) => {
    const { params } = props ?? {};

    return putPutPersonalOrder(params, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type PutPutPersonalOrderMutationResult = NonNullable<
  Awaited<ReturnType<typeof putPutPersonalOrder>>
>;

export type PutPutPersonalOrderMutationError = ErrorType<unknown>;

export const usePutPutPersonalOrder = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof putPutPersonalOrder>>,
      TError,
      { params?: PutPutPersonalOrderParams },
      TContext
    >;
    request?: SecondParameter<typeof axiosInstance>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof putPutPersonalOrder>>,
  TError,
  { params?: PutPutPersonalOrderParams },
  TContext
> => {
  const mutationOptions = getPutPutPersonalOrderMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
export const putPutCompanyOrder = (
  params?: PutPutCompanyOrderParams,
  options?: SecondParameter<typeof axiosInstance>,
) => {
  return axiosInstance<null>(
    { url: `https://localhost:7035/PutCompanyOrder`, method: "PUT", params },
    options,
  );
};

export const getPutPutCompanyOrderMutationOptions = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof putPutCompanyOrder>>,
    TError,
    { params?: PutPutCompanyOrderParams },
    TContext
  >;
  request?: SecondParameter<typeof axiosInstance>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof putPutCompanyOrder>>,
  TError,
  { params?: PutPutCompanyOrderParams },
  TContext
> => {
  const mutationKey = ["putPutCompanyOrder"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof putPutCompanyOrder>>,
    { params?: PutPutCompanyOrderParams }
  > = (props) => {
    const { params } = props ?? {};

    return putPutCompanyOrder(params, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type PutPutCompanyOrderMutationResult = NonNullable<
  Awaited<ReturnType<typeof putPutCompanyOrder>>
>;

export type PutPutCompanyOrderMutationError = ErrorType<unknown>;

export const usePutPutCompanyOrder = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof putPutCompanyOrder>>,
      TError,
      { params?: PutPutCompanyOrderParams },
      TContext
    >;
    request?: SecondParameter<typeof axiosInstance>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof putPutCompanyOrder>>,
  TError,
  { params?: PutPutCompanyOrderParams },
  TContext
> => {
  const mutationOptions = getPutPutCompanyOrderMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
